version: "3.9"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mytime
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379
    restart:
      always
  # backend:
  #   image: backend
  #   ports:
  #     - 3001:3001
  #   command: ["./wait-for-it.sh", "db:5432", "--", "npm", 'start']
  #   depends_on:
  #     - db
  #     - redis
  #   environment:
  #     - DB_HOST= db
  #     - REDIS_HOST= redis
  #     - DATABASE_URL=postgres://postgres:password@db:5432/mytime
  #     - PORT=3001
  #   volumes:
  #     - ./api:/usr/app/
  #     - /usr/app/node_modules
  #   networks:
  #     - webnet