version: "2"
services:
  # backend:
  #   image: amywangg/mytime-backend
  #   ports:
  #     - 80:3001
  #   command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=postgres://postgres:password@db:5432/mytime
  #     - PORT=3001
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mytime
